### PR TITLE
clean meson build system, update PO to include desktop & appdata file…

### LINKED ISSUE #37: Wrong icon after installation
screenshot from 2017-05-18 22 13 16

When explicitly searching for "Nimbus" is OK, though.

### PR DESCRIPTION
**Pull request by bil-elmoussaoui**
This PR includes : 
- Clean build system, add icon cache refreshing fixes #37 
- Include appdata & desktop file on i18n
- Few markdown fixes

### CODE REVIEW

**Comment by danrabbit** [comment]
Hey thanks for your branch. I would appreciate it if you would break this up into several smaller pull requests with each PR addressing only a single issue. As it is now, this one commit touches too many unrelated things. I would like to review each change separately.

**Comment by bil-elmoussaoui** [comment]
How would you like me to break it up? For now, the meson build system & i18n are the same things, at least for me. Anyway, i don't have any issue separating this PR into smaller ones

**Comment by danrabbit** [comment]
Each PR should represent one fix. One for the readme, one for i18n, one for cache changes, one for code style changes, etc.

I can see right now it looks like you're trying to change my meson file to 2 space indent and that's not something I would merge. So this means any other changes you would make are now blocked by this unrelated change. Each PR should only change one thing to avoid these kind of blocks

**Comment by bil-elmoussaoui** [comment]
Alright, I will make that PR right now :) for the 2 space indent, it just seems to be common by meson users.

**Pull request closed without merging**
